# Implementación de Hugging face

In [3]:
from __future__ import print_function

In [4]:
import torch
torch.cuda.is_available()

True

In [5]:
from transformers import GPT2Model, GPT2Tokenizer

In [6]:
# Load pretrained model/tokenizer
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2Model.from_pretrained('gpt2')

In [7]:
# Encode text

input_ids = torch.tensor([tokenizer.encode("Here is some text to encode", add_special_tokens=True)])  # Add special tokens takes care of adding [CLS], [SEP], <s>... tokens in the right way for each model.
print(input_ids)

with torch.no_grad():
    last_hidden_states = model(input_ids)[0]  # Models outputs are now tuples
    print(last_hidden_states)

tensor([[ 4342,   318,   617,  2420,   284, 37773]])
tensor([[[-0.0025,  0.0606, -0.3074,  ..., -0.1128, -0.1026, -0.0213],
         [-0.0085,  0.1233,  0.0123,  ...,  0.2896,  0.6784,  0.2019],
         [-0.1504,  0.1876, -0.7935,  ..., -0.0142, -0.1023,  0.0580],
         [-0.4212,  0.2070, -1.7362,  ..., -0.1389, -0.4477, -0.0204],
         [-0.0037, -0.0273, -0.2224,  ..., -0.3865,  0.0549, -0.5796],
         [-0.0419,  0.2079, -1.0730,  ...,  0.0319,  0.2747, -0.5939]]])


In [8]:
tokenizer.decode(input_ids[0])

'Here is some text to encode'

In [70]:
with torch.no_grad():
    print(len(model(input_ids)))
    print(model(input_ids)[0].size())
    print(model(input_ids)[0])    

2
torch.Size([1, 6, 768])
tensor([[[-0.0025,  0.0606, -0.3074,  ..., -0.1128, -0.1026, -0.0213],
         [-0.0085,  0.1233,  0.0123,  ...,  0.2896,  0.6784,  0.2019],
         [-0.1504,  0.1876, -0.7935,  ..., -0.0142, -0.1023,  0.0580],
         [-0.4212,  0.2070, -1.7362,  ..., -0.1389, -0.4477, -0.0204],
         [-0.0037, -0.0273, -0.2224,  ..., -0.3865,  0.0549, -0.5796],
         [-0.0419,  0.2079, -1.0730,  ...,  0.0319,  0.2747, -0.5939]]])


## GPT2LMHeadModel

In [9]:
import torch
from transformers import GPT2Tokenizer, GPT2LMHeadModel

In [10]:
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2LMHeadModel.from_pretrained('gpt2')

In [13]:
input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
outputs = model(input_ids, labels=input_ids)
loss, logits = outputs[:2]

In [15]:
logits

tensor([[[ -35.2362,  -35.3266,  -38.9753,  ...,  -44.4645,  -43.9974,
           -36.4580],
         [-112.6171, -114.5832, -116.5725,  ..., -119.0128, -118.8059,
          -111.6917],
         [ -88.7435,  -89.8644,  -93.1977,  ...,  -92.3839,  -96.1783,
           -92.1273],
         [ -85.1646,  -88.3379,  -92.8703,  ...,  -99.8017,  -94.7657,
           -90.9330],
         [-116.7281, -119.3950, -121.7259,  ..., -129.1003, -124.6102,
          -121.6092],
         [ -77.4425,  -80.4463,  -88.0497,  ...,  -96.2564,  -93.6345,
           -84.0666]]], grad_fn=<UnsafeViewBackward>)

In [21]:
tokenizer.decode(input_ids[0])

'Hello, my dog is cute'

In [25]:
input_ids.size()

torch.Size([1, 6])

In [30]:
input_ids[0]

tensor([15496,    11,   616,  3290,   318, 13779])

In [34]:
outputs[0]

tensor(3.9902, grad_fn=<NllLossBackward>)

In [35]:
outputs[1]

tensor([[[ -35.2362,  -35.3266,  -38.9753,  ...,  -44.4645,  -43.9974,
           -36.4580],
         [-112.6171, -114.5832, -116.5725,  ..., -119.0128, -118.8059,
          -111.6917],
         [ -88.7435,  -89.8644,  -93.1977,  ...,  -92.3839,  -96.1783,
           -92.1273],
         [ -85.1646,  -88.3379,  -92.8703,  ...,  -99.8017,  -94.7657,
           -90.9330],
         [-116.7281, -119.3950, -121.7259,  ..., -129.1003, -124.6102,
          -121.6092],
         [ -77.4425,  -80.4463,  -88.0497,  ...,  -96.2564,  -93.6345,
           -84.0666]]], grad_fn=<UnsafeViewBackward>)

In [38]:
len(outputs[2])

12

In [40]:
outputs[2][0].size()

torch.Size([2, 1, 12, 6, 64])

In [44]:
outputs[2][0][0][0][0][0]

tensor([-1.2526,  2.3200,  0.1722, -0.2306,  0.6758,  0.5674, -0.1700,  0.1725,
        -2.1884,  0.9263,  0.9814,  0.1263,  0.3077,  0.1170, -0.4522, -0.7159,
         0.7599,  0.2335,  2.4277,  0.1404, -0.9806,  0.0032, -0.6595, -0.9685,
         0.5280, -0.7793, -0.6243,  0.2704, -0.4567, -0.9123,  2.3245, -0.3359,
        -0.7136,  0.0162, -0.0382, -0.4768,  0.8897,  0.2845, -0.1005,  0.0338,
         0.0510, -0.0248, -0.7672,  0.3191, -0.4766, -0.2802,  0.8109, -0.1948,
         0.2800,  0.4119, -0.1979, -0.4096,  1.8527,  0.8029, -0.2051,  1.5191,
        -0.2883,  0.0487, -0.9122,  0.0639, -0.3965, -1.0076, -0.1897,  1.3219],
       grad_fn=<SelectBackward>)

# Text Generation

In [1]:
import torch
from transformers import GPT2Tokenizer, GPT2LMHeadModel

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.cuda.is_available(), device

(True, device(type='cuda'))

In [18]:
tokenizer_class = GPT2Tokenizer
model_class = GPT2LMHeadModel

MAX_LENGTH = 10000

def adjust_length_to_model(length, max_sequence_length):
    if length < 0 and max_sequence_length > 0:
        length = max_sequence_length
    elif 0 < max_sequence_length < length:
        length = max_sequence_length  # No generation bigger than model size
    elif length < 0:
        length = MAX_LENGTH  # avoid infinite loop
    return length


tokenizer = tokenizer_class.from_pretrained('gpt2')
model = model_class.from_pretrained('gpt2')
model.to(device)

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0): Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (1): Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): Laye

In [19]:
text_to_complete = "When I look at the sky, i feel"
text_to_complete

'When I look at the sky, i feel'

In [20]:
encoded_text = tokenizer.encode(text_to_complete,
                                add_special_tokens=False,
                                return_tensors="pt",
                                add_space_before_punct_symbol=True
                               )

In [21]:
encoded_text = encoded_text.to(device)

In [22]:
encoded_text.size()

torch.Size([1, 9])

In [23]:
input_ids = encoded_text

In [24]:
length = 30
length = adjust_length_to_model(length, max_sequence_length=model.config.max_position_embeddings)

output_sequences = model.generate(
    input_ids=input_ids,
    max_length=length + len(encoded_text[0]),
    temperature=1.0,
    top_k=0,
    top_p=0.9,
    num_return_sequences=1,
    repetition_penalty=1.0,
    do_sample=True,
)

Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence


In [25]:
output_sequences

tensor([[ 2215,   314,   804,   379,   262,  6766,    11,  1312,  1254,  2147,
            11,  1312,   655,   765,   284,   766,   340,   526,   198,   198,
          4821,   284, 11735,    11,   366, 15468,   883,   508,   389, 19695,
           290,  7613,    11,  1037,  1854,   416,   644,   484,   466]],
       device='cuda:0')

In [26]:
tokenizer.decode(output_sequences.tolist()[0], clean_up_tokenization_spaces=True)


'When I look at the sky, i feel nothing, i just want to see it."\n\nAccording to Anna, "Sometimes those who are humble and helpful, help others by what they do'

In [27]:
# Remove the batch dimension when returning multiple sequences
if len(output_sequences.shape) > 2:
    output_sequences.squeeze_()

generated_sequences = []

for generated_sequence_idx, generated_sequence in enumerate(output_sequences):
        print("=== GENERATED SEQUENCE {} ===".format(generated_sequence_idx + 1))
        generated_sequence = generated_sequence.tolist()

        # Decode text
        text = tokenizer.decode(generated_sequence, clean_up_tokenization_spaces=True)

        # Add the prompt at the beginning of the sequence. Remove the excess text that was used for pre-processing
        total_sequence = (
            text_to_complete + text[len(tokenizer.decode(encoded_text[0], clean_up_tokenization_spaces=True)) :]
        )

        generated_sequences.append(total_sequence)
        print(total_sequence)

=== GENERATED SEQUENCE 1 ===
When I look at the sky, i feel nothing, i just want to see it."

According to Anna, "Sometimes those who are humble and helpful, help others by what they do
